"""add usage stats to account_deletion_feedback

Revision ID: 57ded9e4631b
Revises: b85b52933998
Create Date: 2026-03-16 15:01:16.386377
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ded9e4631b'
down_revision: Union[str, None] = 'b85b52933998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_deletion_feedback', sa.Column('plan_type', sa.String(length=20), nullable=True))
    op.add_column('account_deletion_feedback', sa.Column('total_videos', sa.Integer(), nullable=True))
    op.add_column('account_deletion_feedback', sa.Column('total_searches', sa.Integer(), nullable=True))
    op.add_column('account_deletion_feedback', sa.Column('storage_used_bytes', sa.BigInteger(), nullable=True))
    op.add_column('account_deletion_feedback', sa.Column('account_age_days', sa.Integer(), nullable=True))
    op.add_column('account_deletion_feedback', sa.Column('subscription_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account_deletion_feedback', 'subscription_history')
    op.drop_column('account_deletion_feedback', 'account_age_days')
    op.drop_column('account_deletion_feedback', 'storage_used_bytes')
    op.drop_column('account_deletion_feedback', 'total_searches')
    op.drop_column('account_deletion_feedback', 'total_videos')
    op.drop_column('account_deletion_feedback', 'plan_type')
    # ### end Alembic commands ###
